sudo: false

git:
  depth: false

services:
  - docker

language: node_js

node_js:
  - "10"

cache:
  yarn: true

before_script:
  - set -e

script:
  - if .travis/build-condition.sh "eq-author"; then AUTHOR_BUILT=true; echo "Author is being built"; pushd eq-author; ./scripts/ci.sh; popd; else echo "Author is NOT being built"; fi
  - if .travis/build-condition.sh "eq-author-api"; then echo "API is being built"; pushd eq-author-api; ./scripts/ci.sh; popd; else echo "API is NOT being built"; fi
  - if .travis/build-condition.sh "eq-publisher"; then echo "Publisher is being built"; pushd eq-publisher; ./scripts/ci.sh; popd; else echo "Publisher is NOT being built"; fi
  - cd eq-author
  - yarn install --frozen-lockfile
  - yarn test:integration
  - yarn test:e2e

deploy:
  local_dir: eq-author/storybook-static
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch:
      - master
    condition:
      - $AUTHOR_BUILT = true

branches:
  only:
    - master